name: DEV ENV

on:
  workflow_dispatch: 

jobs:
  hello:
    runs-on: ubuntu-latest
    environment: DEV
    steps:
      - name: Get Variables
        run: |
          echo "ECR: ${{ secrets.ECR }}"
          echo "APP: ${{ vars.APP }}"
