name: Hello World Workflow

on:
  workflow_dispatch:  # This allows the workflow to be triggered manually

jobs:
  hello:
    runs-on: ubuntu-latest

    steps:
      - name: Print Hello World
        run: echo "Hello, World!"
